### ISSUE TITLE
availability

### ISSUE THREAD

**Issue by khayyak** [DHUniWien/tpen2tei#10]
Hello , is this tool still available to use or not ?

thanks in advance

**Comment by tla** [comment]
Yes, it is available through PyPI as well as here: https://pypi.org/project/tpen2tei/ 

I'm afraid there isn't really any documentation, because I didn't know anyone else would use it!

**Comment by khayyak** [comment]
Thanks for responding.
Yes that's why I asked because I want to use it to convert JSON file to TEI but I can't find any documentation helping me.

**Comment by khayyak** [comment]
I just ask if you can help me in that , I will be thankful

**Comment by tla** [comment]
Briefly: 

    from tpen2tei.parse import from_sc

and then you need to pass a few arguments to the `from_sc` function when you call it:

    def from_sc(jsondata,        # This is the Shared Canvas JSON data for the project that you get from T-PEN
            metadata=None,   # More on this below
            members=None,    # More on this below
            special_chars=None,    # This is used if you have any need for non-Unicode glyphs using the <g> tag
            numeric_parser=None,   # This is used if you want to convert text strings to numeric values e.g. LXIII 
            text_filter=None,   # This is a function you can pass in order to do transcript correction before the conversion to TEI happens. 
                                # It takes a single parameter, which is the transcribed text of an individual line.
            postprocess=None    # This is a function you can pass in order to modify the TEI result after it has been generated. 
                                # It takes a single parameter, which is the etree-parsed TEI document.
    ):

The `metadata` parameter is a key/value dictionary, where the recognised keys are: 
* `short_error` - set this to `True` if you want shorter error/diagnostic output
* `title` - the title of the text, for the TEI header
* `author` - the author of the text, for the TEI header
* `publicationStmt` - the desired contents of the TEI `<publicationStmt>` element
* `msIdentifier` - the `xml:id` to be assigned to this manuscript, usually the sigil it will have in a future critical edition
* `msSettlement`, `msRepository`, `msIdNumber` - the desired contents of these elements in the TEI msDesc header
* `date` - the date when the manuscript was copied
* `location` - the location where the manuscript was copied
* `description` - the description to go into the TEI msDesc header
* `teiSchema` - the URL of the TEI Schema you are using; default is http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng

The `members` parameter is also a dictionary, in the following format, meant to assign responsibility for transcription lines. If it isn't passed, then no responsibility statements are included.

```
 {
  "0": {},  # keep this!
  "1234": {
    "name": "A. Tpen Transcriber",
    "uname": "transcriber@myproject.org",
  },
  [...]
}
```

I hope this helps somewhat!

**Comment by khayyak** [comment]
Thank you , I will try that and I'll tell you what I get . Thank you again.

**Comment by khayyak** [comment]
I got this error : 

48     object, which is the otherwise final parsed TEI document, and modifies it.
     49     """
---> 50     if len(jsondata['sequences']) > 1:
     51         warn("Your data has more than one sequence. Check to see what's going on.", UserWarning)
     52     # Merge the JSON-supplied metadata into the user-supplied. If a user has

TypeError: string indices must be integers

**Comment by tla** [comment]
I'll need to see how you called the function and what data you gave it, otherwise I won't have any idea.

**Comment by khayyak** [comment]
from tpen2tei.parse import from_sc
from_sc('Sample-JSON-file-with-multiple-records-download.json',
        metadata=None,
        members=None,
        special_chars=None,
        numeric_parser=None,
        text_filter=None,
        postprocess=None)


Sample-JSON-file-with-multiple-records-download.json is a JSON file contains this data :
{
  "users": [
    {
      "firstName": "Krish",
      "lastName": "Lee"
    },
    {
      "firstName": "racks",
      "lastName": "jacson"
    },
    {
      "firstName": "denial",
      "lastName": "roast"
    },
  ]
}

**Comment by tla** [comment]
Okay so your JSON file looks like `members` data, not like transcription data. The transcription data should be whatever you downloaded from T-PEN, and it should already have been parsed into a Python dictionary using the Python JSON parser. If you do pass `members` data, it should also be a Python dictionary, not a filename.

**Comment by khayyak** [comment]
can you please give a sample of transcription data because there is some kind of problems in http://www.t-pen.org/TPEN/ so I can't open it.

**Comment by tla** [comment]
There are some samples in the `tests/data` directory of this repository.

**Comment by khayyak** [comment]
Okay thank you very much , so I can't convert any kind of JSON files ? it should be like the samples in testes/data .

**Comment by tla** [comment]
Correct - they need to be the Shared Canvas JSON files as downloaded from T-PEN.

**Comment by khayyak** [comment]
Thank you very much for your help , I really appreciate that. Hope you the best.

cheers
