### ISSUE TITLE
Handle multiple-project manuscripts

### ISSUE THREAD

**Issue by tla** [DHUniWien/tpen2tei#6]
A single MS often needs to be split into multiple T-PEN projects. The resulting JSON files should be recombinable into a single TEI XML output.

**Comment by oftl** [comment]
Those project are merged into single files during moe-data pipeline (see https://ci.stemmaweb.net/teams/main/pipelines/moe-data). The resulting files are pushed to github (here: https://github.com/DHUniWien/MatthewEdessa/tree/master/transcription/tei-xml/*-merged.json.tei.xml).

**Comment by tla** [comment]
OK - if we ever get other users for this module, it might still be worth bringing that functionality into the tpen2tei tree. Let's see how it goes.
